# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: '^/$', priorities: [html], fallback_format: html, prefer_extension: true }
      - { path: '^/api-doc', priorities: [html], fallback_format: html, prefer_extension: true }
      - { path: '^/', priorities: [json, xml], fallback_format: json, prefer_extension: true }
  allowed_methods_listener: true
  param_fetcher_listener: true
  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys
  view:
    view_response_listener: true
    formats:
      rss: false
      json: true
      xml: false
    failed_validation: HTTP_UNPROCESSABLE_ENTITY
    empty_content: HTTP_NO_CONTENT
#fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
