nelmio_cors:
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Authorization']
            allow_credentials: true
            expose_headers: ['Link']
            max_age: 3600